AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin specific exceptions
#

# this rule does not take into account the spacing of commented out lines
Layout/ExtraSpacing:
  Exclude:
    - 'Gemfile'

# no need to add `frozen_string_literal: true` to new scripts/projects
Style/FrozenStringLiteralComment:
  Exclude:
    - 'data/templates/**/*'
